#include "GroupwiseRegistration.h"

int main(int argc, char** argv)
{
	char sphere[1024] = "../../../data/s0.lh.sphere_std.obj";
	
	char tmpDepth[1024] = "../../../data/freesurfer2/s40s0.lh.mid.vv";
	
	char *subjDepth[1024] = {"../../../data/freesurfer2/s40s1.lh.mid.vv", 
							"../../../data/freesurfer2/s40s10.lh.mid.vv",
							"../../../data/freesurfer2/s40s11.lh.mid.vv",
							"../../../data/freesurfer2/s40s12.lh.mid.vv",
							"../../../data/freesurfer2/s40s13.lh.mid.vv",
							"../../../data/freesurfer2/s40s14.lh.mid.vv",
							"../../../data/freesurfer2/s40s15.lh.mid.vv",
							"../../../data/freesurfer2/s40s16.lh.mid.vv",
							"../../../data/freesurfer2/s40s17.lh.mid.vv",
							"../../../data/freesurfer2/s40s18.lh.mid.vv",
							"../../../data/freesurfer2/s40s19.lh.mid.vv",
							"../../../data/freesurfer2/s40s2.lh.mid.vv", 
							"../../../data/freesurfer2/s40s20.lh.mid.vv",
							"../../../data/freesurfer2/s40s21.lh.mid.vv",
							"../../../data/freesurfer2/s40s22.lh.mid.vv",
							"../../../data/freesurfer2/s40s23.lh.mid.vv",
							"../../../data/freesurfer2/s40s24.lh.mid.vv",
							"../../../data/freesurfer2/s40s25.lh.mid.vv",
							"../../../data/freesurfer2/s40s26.lh.mid.vv",
							"../../../data/freesurfer2/s40s27.lh.mid.vv",
							"../../../data/freesurfer2/s40s28.lh.mid.vv",
							"../../../data/freesurfer2/s40s29.lh.mid.vv",
							"../../../data/freesurfer2/s40s3.lh.mid.vv", 
							"../../../data/freesurfer2/s40s30.lh.mid.vv",
							"../../../data/freesurfer2/s40s31.lh.mid.vv",
							"../../../data/freesurfer2/s40s32.lh.mid.vv",
							"../../../data/freesurfer2/s40s33.lh.mid.vv",
							"../../../data/freesurfer2/s40s34.lh.mid.vv",
							"../../../data/freesurfer2/s40s35.lh.mid.vv",
							"../../../data/freesurfer2/s40s4.lh.mid.vv", 
							"../../../data/freesurfer2/s40s5.lh.mid.vv", 
							"../../../data/freesurfer2/s40s6.lh.mid.vv", 
							"../../../data/freesurfer2/s40s7.lh.mid.vv", 
							"../../../data/freesurfer2/s40s8.lh.mid.vv", 
							"../../../data/freesurfer2/s40s9.lh.mid.vv"	};
	
	char *coeff[1024] = {"../../../data/freesurfer2/coeff/coeff_s40s1.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s10.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s11.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s12.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s13.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s14.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s15.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s16.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s17.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s18.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s19.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s2.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s20.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s21.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s22.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s23.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s24.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s25.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s26.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s27.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s28.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s29.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s3.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s30.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s31.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s32.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s33.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s34.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s35.lh.mid.txt",
						"../../../data/freesurfer2/coeff/coeff_s40s4.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s5.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s6.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s7.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s8.lh.mid.txt", 
						"../../../data/freesurfer2/coeff/coeff_s40s9.lh.mid.txt"
	};
	
	char *correspondence[1024] = {"../../../data/freesurfer2/corr_s40s1.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s1.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s10.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s10.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s11.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s11.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s12.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s12.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s13.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s13.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s14.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s14.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s15.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s15.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s16.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s16.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s17.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s17.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s18.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s18.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s19.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s19.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s2.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s2.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s20.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s20.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s21.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s21.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s22.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s22.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s23.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s23.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s24.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s24.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s25.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s25.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s26.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s26.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s27.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s27.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s28.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s28.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s29.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s29.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s3.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s3.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s30.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s30.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s31.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s31.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s32.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s32.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s33.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s33.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s34.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s34.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s35.lh.mid.txt",     
								"../../../data/freesurfer2/disp_corr_s40s35.lh.mid.txt",
								"../../../data/freesurfer2/corr_s40s4.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s4.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s5.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s5.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s6.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s6.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s7.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s7.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s8.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s8.lh.mid.txt", 
								"../../../data/freesurfer2/corr_s40s9.lh.mid.txt",      
								"../../../data/freesurfer2/disp_corr_s40s9.lh.mid.txt"
	};

	GroupwiseRegistration *r = new GroupwiseRegistration(sphere, tmpDepth, subjDepth, coeff, correspondence, 35, "log.txt");
	r->saveLDeformation("group.txt");
	for (int i = 0; i < 35; i++)
	{
		char fn[1024];
		sprintf(fn, "%s", &coeff[i][32]);
		r->saveLCoeff(fn, i);
	}

	return 0;
}